FROM python:3.13.1-slim-bullseye

# Tắt tạo file .pyc và thiết lập chế độ unbuffered cho Python
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Cài đặt các gói cần thiết cho build, ví dụ bcrypt, psycopg2, v.v.
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libffi-dev \
    libpq-dev \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*

# Tạo thư mục /app và đặt làm thư mục làm việc
WORKDIR /app

# Copy file requirements.txt vào container
COPY requirements.txt /app/

# Cài đặt các package cần thiết từ requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy toàn bộ mã nguồn vào thư mục làm việc của container
COPY . /app

# Mở cổng 8000 để truy cập FastAPI
EXPOSE 8000

# Chạy migration và khởi động server FastAPI với uvicorn
CMD alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload
